Enhance Terraform workflow: add report uploads and improve plan output handling

diff --git a/.github/workflows/terraform.yaml b/.github/workflows/terraform.yaml
--- a/.github/workflows/terraform.yaml
+++ b/.github/workflows/terraform.yaml
@@ -29,7 +29,7 @@ jobs:
         - name: TruffleHog OSS
           uses: trufflesecurity/trufflehog@v3.96.0
           with:
-            extra_args: --results=verified,unknown
+            extra_args: --results=verified,unknown --json > trufflehog-report.json
 
         - uses: terraform-linters/setup-tflint@v6
           name: Setup TFLint
@@ -46,7 +46,17 @@ jobs:
             GITHUB_TOKEN: ${{ github.token }}
 
         - name: Run TFLint
-          run: tflint -f compact  
+          run: tflint -f compact > tflint-report.txt
+
+        - name: Upload Scan Reports
+          if: always()
+          uses: actions/upload-artifact@v7
+          with:
+            name: scan-reports
+            path: |
+              trufflehog-report.json
+              tflint-report.txt
+            retention-days: 5
 
 
   plan:
@@ -58,6 +68,10 @@ jobs:
       defaults:
         run:
             working-directory: environment/dev
+
+      outputs:
+        changes: ${{ steps.planid.outputs.changes }}
+        status: ${{ steps.planid.outputs.status}}
 
       steps:
 
@@ -86,16 +100,40 @@ jobs:
           run: terraform validate
 
         - name: Terraform Plan
-          run: terraform plan
+          id: planid
+          run: |
+            set +e
+            terraform plan -detailed-exitcode -out=tfplan
+
+            EXIT_CODE=$?
+
+            if [ "$EXIT_CODE" -eq 0 ]; then
+              echo "status=success" >> "$GITHUB_OUTPUT"
+              echo "changes=false" >> "$GITHUB_OUTPUT"
+
+            elif [ "$EXIT_CODE" -eq 2 ]; then
+              echo "status=success" >> "$GITHUB_OUTPUT"
+              echo "changes=true" >> "$GITHUB_OUTPUT"
+
+            else
+              echo "status=failed" >> "$GITHUB_OUTPUT"
+              echo "changes=false" >> "$GITHUB_OUTPUT"
+              exit "$EXIT_CODE"
+            fi
           
+        - name: Upload Plan Artifact
+          uses: actions/upload-artifact@v7
+          with:
+            name: terraform-plan
+            path: tfplan
 
   apply:
-      if: github.ref == 'refs/heads/main'
       name: Terraform Apply
       needs: plan
+      if: github.ref == 'refs/heads/main' && needs.plan.outputs.changes == 'true' && needs.plan.outputs.status == 'success'
       runs-on: ubuntu-latest
       environment:
-        name: production
+        name: production 
       defaults:
         run:
             working-directory: environment/dev
@@ -122,9 +160,15 @@ jobs:
 
         - name: Terraform Init
           run: terraform init
+
+        - name: Download Plan Artifact
+          uses: actions/download-artifact@v8
+          with:
+            name: terraform-plan
+            path: tfplan
           
         - name: Terraform Apply
-          run: terraform apply -auto-approve
+          run: terraform apply -auto-approve tfplan
 
 
 
